version: '3.9'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssword123
    volumes:
      - mssql-db-vol:/var/opt/mssql
volumes:
  mssql-db-vol: